num_1="50.36";
tuplas=(1,2.36,"cesar");
listas=[3,23,65,"alejo"];
diccionarios={"dato1":123,"dato2":456};
conjuntos={4,6,8,203,"soto"};
print(type(tuplas));
num2=45;
variable=float (input("digite el valor de la variable:"));
variable2=float(input("digite un valor entero:"));
resultado=variable**variable2;
print("el resulatado de la operacion es:",resultado);
resultado=pow(variable,variable2);